[tool.poetry]
name = "bankingconversion"
version = "0.1.0"
description = ""
authors = ["Mark Sheehan <mark.sheehan@hellopupil.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
